
boot_file: "output/factorisco/kernel/debug_boot_machine_code.txt"
os_file: "output/factorisco/kernel/ecall_01_machine_code.txt"
ecall_file: "output/factorisco/kernel/os_02_machine_code.txt"

# pointers and addresses
boot_address: 135680
os_address: 139776
ecall_address: 131584
user_program_addresses: [147968, 152064, 156160, 160256]

kernel_mode_address: 15
clock_address: 16
